Log collector
open-io/openio-netdata-plugins pull request #35
Opened 2020-01-21 11:09 UTC by vdombrovski

2020-02-10 17:04 UTC, fatpat requested changes

2020-02-11 05:37 UTC, fatpat requested changes

2020-02-11 05:37 UTC, fatpat commented on cmd/log.plugin/log.plugin.go
> +	bandwidthIn := netdata.NewChart("log", "bandwidth_in", "", "Bandwidth in", "kB", family, "")
bandwidth with a unit of `kB`, should it not be `kBps` or `kbps` ?

2020-02-12 05:51 UTC, fatpat requested changes
```
BEGIN log.response_time
SET 'min_PUT_OPENIO-oioswift-0.-' = 0
SET 'max_DELETE_OPENIO-rawx-0' = 143
SET 'max_PUT_OPENIO-rawx-0' = 36891
SET 'avg_DELETE_OPENIO-rawx-0' = 0
SET 'avg_M2_CREATE_OPENIO-meta2-0' = 0
SET 'avg_PUT_OPENIO-rawx-0' = 0
SET 'avg_M1_LINK_OPENIO-meta1-0' = 0
SET 'min_M2_PUT_OPENIO-meta2-0' = 0
SET 'max_M2_PUT_OPENIO-meta2-0' = 140344
SET 'min_M1_LINK_OPENIO-meta1-0' = 0
SET 'max_M1_LIST_OPENIO-meta1-0' = 28969
SET 'max_M2_CREATE_OPENIO-meta2-0' = 275720
SET 'avg_PUT_OPENIO-oioswift-0.-' = 0
SET 'min_M1_LIST_OPENIO-meta1-0' = 0
SET 'avg_M1_LIST_OPENIO-meta1-0' = 0
SET 'avg_PUT_OPENIO-oioswift-0.put-object' = 0
SET 'avg_M2_PUT_OPENIO-meta2-0' = 0
SET 'min_M2_CREATE_OPENIO-meta2-0' = 0
SET 'min_DB_PGET_OPENIO-meta2-0' = 0
SET 'min_DELETE_OPENIO-rawx-0' = 0
SET 'max_PUT_OPENIO-oioswift-0.put-object' = 10.0754
SET 'avg_DB_PGET_OPENIO-meta2-0' = 0
SET 'min_PUT_OPENIO-oioswift-0.put-object' = 0
SET 'max_PUT_OPENIO-oioswift-0.-' = 10.0071
SET 'max_M1_LINK_OPENIO-meta1-0' = 220
SET 'max_DB_PGET_OPENIO-meta2-0' = 196895
SET 'min_PUT_OPENIO-rawx-0' = 0
```

2020-02-12 05:51 UTC, fatpat commented on log/log.go
> +			reqName := s[method] + "_" + name + tagString
in line 252 a dot is used to prefix the name whereas here an underscore is used. Please use dot everywhere to be consistent (better for regex parsing in prometheus relabelling phase)

2020-10-16 07:35 UTC, cdelgehier commented
Can we close this one ? @fatpat

2020-10-17 03:38 UTC, closed without merging